#!/usr/bin/env node

// Embed the shared sources into each runtime. Run via: npm run embed
// (from ts/), or: node ts/embed-grammar.js. `--check` writes nothing and
// exits 1 when a runtime's copy differs from its source, naming it.
//
// Two shared sources live at the repository root, and every runtime
// carries them VERBATIM:
//
// - alchemy-grammar.jsonic, the grammar document, copied between the
//   `--- BEGIN/END EMBEDDED alchemy-grammar.jsonic ---` markers of each
//   runtime's grammar source, as a string literal. Never hand-edit
//   between the markers.
// - stdlib/*.alc, the standard library's own definitions, carried by each
//   runtime as a package-local copy, because a published package (a
//   crate, an npm package, a Go module) holds nothing above its own root:
//   file for file in a directory (Rust's rs/stdlib/, Go's go/stdlib/ for
//   go:embed), or as one generated module (TypeScript's
//   ts/src/stdlib/sources.ts, the files as template literals). Never edit
//   a copy.
//
// Each runtime also holds its copies to the sources in its own tests
// (Rust: rs/tests/shared_sources_test.rs; TypeScript:
// ts/test/shared-sources.test.ts; Go: go/shared_sources_test.go), so a
// forgotten embed fails there.
//
// The targets are lists: a runtime adds its entry to GRAMMAR_TARGETS,
// STDLIB_DIRS or STDLIB_MODULES and nothing else changes. The Go port's
// are a raw string in go/alchemy.go and the directory go/stdlib/ (which
// the Go module's own `go run ./internal/embed` writes the same way).
//
// scripts/embed.js, which the root Makefile's `make embed` runs, is a
// one-line shim that runs this file.
//
// No dependencies: Node's fs and path only.

const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const GRAMMAR_FILE = path.join(ROOT, 'alchemy-grammar.jsonic')
const STDLIB_DIR = path.join(ROOT, 'stdlib')

const BEGIN = '// --- BEGIN EMBEDDED alchemy-grammar.jsonic ---'
const END = '// --- END EMBEDDED alchemy-grammar.jsonic ---'

const check = process.argv.includes('--check')
let drift = 0

const grammar = fs.readFileSync(GRAMMAR_FILE, 'utf8')

// A Rust raw string has no escapes, so the grammar goes in verbatim. Its
// token names open with `"#`, so two hashes is the floor.
function rustLiteral(text) {
  if (text.includes('"##')) {
    throw new Error('the grammar contains `"##`, incompatible with the r## raw string')
  }
  return 'pub const GRAMMAR_TEXT: &str = r##"\n' + text + '"##;\n'
}

// A JavaScript template literal: the backslash, the backtick and `${`
// are the only characters it reads specially.
function templateEscape(text) {
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

// The grammar as a TypeScript template literal. It opens with a line
// feed, as the Rust raw string does, so the text the runtime holds is
// the file's with a newline before it in both.
function tsLiteral(text) {
  return 'const grammarText = `\n' + templateEscape(text) + '`\n'
}

// The grammar as a Go raw string. A raw string has no escapes and cannot
// hold a backquote, so each backquote is spliced in as an interpreted
// "`" between two raw strings: the constant's value is the file's text
// exactly. It opens with a line feed, as the others do, and a blank line
// separates it from the end marker (go/internal/embed's GoLiteral writes
// the same text).
function goLiteral(text) {
  return 'const grammarText = `\n' + text.split('`').join('` + "`" + `') + '`\n\n'
}

const GRAMMAR_TARGETS = [
  { file: path.join(ROOT, 'rs', 'src', 'grammar.rs'), literal: rustLiteral },
  { file: path.join(ROOT, 'ts', 'src', 'grammar.ts'), literal: tsLiteral },
  { file: path.join(ROOT, 'go', 'alchemy.go'), literal: goLiteral },
]

// Directories that hold the library file for file.
const STDLIB_DIRS = [path.join(ROOT, 'rs', 'stdlib'), path.join(ROOT, 'go', 'stdlib')]

// Generated modules that hold the whole library, by the name its spans
// carry (`stdlib/<file>.alc`), in file-name order.
function tsStdlibModule(files) {
  let out =
    '/* Copyright (c) 2026 tabnas, MIT License */\n\n' +
    '// GENERATED by ts/embed-grammar.js (npm run embed) from stdlib/*.alc at\n' +
    '// the repository root. Never edit: edit the .alc file and run the embed.\n' +
    '// test/shared-sources.test.ts holds this module to the files.\n\n' +
    '// The embedded library sources, by the file name their spans carry.\n' +
    'export const SOURCES: ReadonlyArray<readonly [string, string]> = [\n'
  for (const [name, text] of files) {
    out += '  [\n    ' + JSON.stringify('stdlib/' + name) + ',\n    `' + templateEscape(text) + '`,\n  ],\n'
  }
  return out + ']\n'
}

const STDLIB_MODULES = [{ file: path.join(ROOT, 'ts', 'src', 'stdlib', 'sources.ts'), module: tsStdlibModule }]

function write(file, text) {
  const was = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
  if (was === text) return
  const name = path.relative(ROOT, file)
  if (check) {
    console.error(`${name} differs from its source: run npm run embed (in ts/) or make embed`)
    drift++
    return
  }
  fs.writeFileSync(file, text)
  console.log('embedded', name)
}

for (const { file, literal } of GRAMMAR_TARGETS) {
  const src = fs.readFileSync(file, 'utf8')
  const start = src.indexOf(BEGIN)
  const end = src.indexOf(END)
  if (-1 === start || -1 === end || end < start) {
    throw new Error('embed markers not found in ' + file)
  }
  write(file, src.substring(0, start) + BEGIN + '\n' + literal(grammar) + src.substring(end))
}

const sources = fs
  .readdirSync(STDLIB_DIR)
  .filter((name) => name.endsWith('.alc'))
  .sort()
for (const dir of STDLIB_DIRS) {
  for (const name of sources) {
    write(path.join(dir, name), fs.readFileSync(path.join(STDLIB_DIR, name), 'utf8'))
  }
  for (const name of fs.readdirSync(dir).filter((name) => name.endsWith('.alc'))) {
    if (!sources.includes(name)) {
      const stale = path.relative(ROOT, path.join(dir, name))
      if (check) {
        console.error(`${stale} has no source in stdlib/: run npm run embed (in ts/) or make embed`)
        drift++
      } else {
        fs.unlinkSync(path.join(dir, name))
        console.log('removed', stale)
      }
    }
  }
}

const files = sources.map((name) => [name, fs.readFileSync(path.join(STDLIB_DIR, name), 'utf8')])
for (const { file, module } of STDLIB_MODULES) {
  write(file, module(files))
}

if (drift > 0) process.exit(1)
if (check) console.log('embedded copies match their sources')
